#!/bin/env bash

spotify() {
    local factor="$1"
    local args="$2"

    shift
    printf "Running spotify with --force-device-scale-factor=%s %s\n" $factor $args
    /opt/spotify/spotify --force-device-scale-factor=$factor $args
}

spotify ${SPOTIFY_SCALE_FACTOR:-2.0} "${@:1}"
